extends Node
# Массив строк зависит от языка
onready var item_table = get_node("/root/ItemTable")

onready var names = {
		item_table.Ids.COPPER_ORE : tr("COPPER_ORE"),
		item_table.Ids.IRON_ORE : tr("IRON_ORE"),
		item_table.Ids.SILVER_ORE : tr("SILVER_ORE"),
		item_table.Ids.GOLDEN_ORE : tr("GOLDEN_ORE"),
		item_table.Ids.FANTASIUM_ORE : tr("FANTASIUM_ORE"),
		item_table.Ids.COPPER_INGOT : tr("COPPER_INGOT"),
		item_table.Ids.IRON_INGOT : tr("IRON_INGOT"),
		item_table.Ids.SILVER_INGOT : tr("SILVER_INGOT"),
		item_table.Ids.GOLDEN_INGOT: tr("GOLDEN_INGOT"),
		item_table.Ids.FANTASIUM_INGOT: tr("FANTASIUM_INGOT"),
		item_table.Ids.COPPER_BATTLE_AXE : tr("COPPER_BATTLE_AXE"),
		item_table.Ids.IRON_BATTLE_AXE : tr("IRON_BATTLE_AXE"),
		item_table.Ids.SILVER_BATTLE_AXE : tr("SILVER_BATTLE_AXE"),
		item_table.Ids.GOLDEN_BATTLE_AXE : tr("GOLDEN_BATTLE_AXE"),
		item_table.Ids.FANTASIUM_BATTLE_AXE : tr("FANTASIUM_BATTLE_AXE"),
		item_table.Ids.COPPER_DAGGER : tr("COPPER_DAGGER"),
		item_table.Ids.IRON_DAGGER : tr("IRON_DAGGER"),
		item_table.Ids.SILVER_DAGGER : tr("SILVER_DAGGER"),
		item_table.Ids.GOLDEN_DAGGER : tr("GOLDEN_DAGGER"),
		item_table.Ids.FANTASIUM_DAGGER : tr("FANTASIUM_DAGGER"),
		item_table.Ids.COPPER_HALBERD : tr("COPPER_HALBERD"),
		item_table.Ids.IRON_HALBERD : tr("IRON_HALBERD"),
		item_table.Ids.SILVER_HALBERD : tr("SILVER_HALBERD"),
		item_table.Ids.GOLDEN_HALBERD : tr("GOLDEN_HALBERD"),
		item_table.Ids.FANTASIUM_HALBERD : tr("FANTASIUM_HALBERD"),
		item_table.Ids.COPPER_LONGSWORD : tr("COPPER_LONGSWORD"),
		item_table.Ids.IRON_LONGSWORD : tr("IRON_LONGSWORD"),
		item_table.Ids.SILVER_LONGSWORD : tr("SILVER_LONGSWORD"),
		item_table.Ids.GOLDEN_LONGSWORD : tr("GOLDEN_LONGSWORD"),
		item_table.Ids.FANTASIUM_LONGSWORD : tr("FANTASIUM_LONGSWORD"),
		item_table.Ids.COPPER_RAPIER : tr("COPPER_RAPIER"),
		item_table.Ids.IRON_RAPIER : tr("IRON_RAPIER"),
		item_table.Ids.SILVER_RAPIER : tr("SILVER_RAPIER"),
		item_table.Ids.GOLDEN_RAPIER : tr("GOLDEN_RAPIER"),
		item_table.Ids.FANTASIUM_RAPIER : tr("FANTASIUM_RAPIER"),

#		item_table.Ids.COPPER_BATTLE_AXE_BLADE : tr("BATTLE_AXE_BLADE"),
#		item_table.Ids.IRON_BATTLE_AXE_BLADE : tr("BATTLE_AXE_BLADE"),
#		item_table.Ids.SILVER_BATTLE_AXE_BLADE : tr("BATTLE_AXE_BLADE"),
#		item_table.Ids.GOLDEN_BATTLE_AXE_BLADE : tr("BATTLE_AXE_BLADE"),
#		item_table.Ids.FANTASIUM_BATTLE_AXE_BLADE : tr("BATTLE_AXE_BLADE"),
#		item_table.Ids.BATTLE_AXE_HANDLE : tr("BATTLE_AXE_HANDLE"),
#
#		item_table.Ids.COPPER_DAGGER_BLADE : tr("DAGGER_BLADE"),
#		item_table.Ids.IRON_DAGGER_BLADE : tr("DAGGER_BLADE"),
#		item_table.Ids.SILVER_DAGGER_BLADE : tr("DAGGER_BLADE"),
#		item_table.Ids.GOLDEN_DAGGER_BLADE : tr("DAGGER_BLADE"),
#		item_table.Ids.FANTASIUM_DAGGER_BLADE : tr("DAGGER_BLADE"),
#		item_table.Ids.DAGGER_HANDLE : tr("DAGGER_HANDLE"),
#		item_table.Ids.COPPER_DAGGER_BOLSTER : tr("DAGGER_BOLSTER"),
#		item_table.Ids.IRON_DAGGER_BOLSTER : tr("DAGGER_BOLSTER"),
#		item_table.Ids.SILVER_DAGGER_BOLSTER : tr("DAGGER_BOLSTER"),
#		item_table.Ids.GOLDEN_DAGGER_BOLSTER : tr("DAGGER_BOLSTER"),
#		item_table.Ids.FANTASIUM_DAGGER_BOLSTER : tr("DAGGER_BOLSTER"),
#		item_table.Ids.COPPER_DAGGER_GUARD : tr("DAGGER_GUARD"),
#		item_table.Ids.IRON_DAGGER_GUARD : tr("DAGGER_GUARD"),
#		item_table.Ids.SILVER_DAGGER_GUARD : tr("DAGGER_GUARD"),
#		item_table.Ids.GOLDEN_DAGGER_GUARD : tr("DAGGER_GUARD"),
#		item_table.Ids.FANTASIUM_DAGGER_GUARD : tr("DAGGER_GUARD"),
#
#		item_table.Ids.COPPER_HALBERD_BLADE : tr("HALBERD_BLADE"),
#		item_table.Ids.IRON_HALBERD_BLADE : tr("HALBERD_BLADE"),
#		item_table.Ids.SILVER_HALBERD_BLADE : tr("HALBERD_BLADE"),
#		item_table.Ids.GOLDEN_HALBERD_BLADE : tr("HALBERD_BLADE"),
#		item_table.Ids.FANTASIUM_HALBERD_BLADE : tr("HALBERD_BLADE"),
#		item_table.Ids.HALBERD_HANDLE : tr("HALBERD_HANDLE"),
#		item_table.Ids.COPPER_HALBERD_BOLSTER : tr("HALBERD_BOLSTER"),
#		item_table.Ids.IRON_HALBERD_BOLSTER : tr("HALBERD_BOLSTER"),
#		item_table.Ids.SILVER_HALBERD_BOLSTER : tr("HALBERD_BOLSTER"),
#		item_table.Ids.GOLDEN_HALBERD_BOLSTER : tr("HALBERD_BOLSTER"),
#		item_table.Ids.FANTASIUM_HALBERD_BOLSTER : tr("HALBERD_BOLSTER"),
#
#		item_table.Ids.COPPER_LONGSWORD_BLADE : tr("LONGSWORD_BLADE"),
#		item_table.Ids.IRON_LONGSWORD_BLADE : tr("LONGSWORD_BLADE"),
#		item_table.Ids.SILVER_LONGSWORD_BLADE : tr("LONGSWORD_BLADE"),
#		item_table.Ids.GOLDEN_LONGSWORD_BLADE : tr("LONGSWORD_BLADE"),
#		item_table.Ids.FANTASIUM_LONGSWORD_BLADE : tr("LONGSWORD_BLADE"),
#		item_table.Ids.LONGSWORD_HANDLE : tr("LONGSWORD_HANDLE"),
#		item_table.Ids.COPPER_LONGSWORD_BOLSTER : tr("LONGSWORD_BOLSTER"),
#		item_table.Ids.IRON_LONGSWORD_BOLSTER : tr("LONGSWORD_BOLSTER"),
#		item_table.Ids.SILVER_LONGSWORD_BOLSTER : tr("LONGSWORD_BOLSTER"),
#		item_table.Ids.GOLDEN_LONGSWORD_BOLSTER : tr("LONGSWORD_BOLSTER"),
#		item_table.Ids.FANTASIUM_LONGSWORD_BOLSTER : tr("LONGSWORD_BOLSTER"),
#		item_table.Ids.COPPER_LONGSWORD_GUARD : tr("LONGSWORD_GUARD"),
#		item_table.Ids.IRON_LONGSWORD_GUARD : tr("LONGSWORD_GUARD"),
#		item_table.Ids.SILVER_LONGSWORD_GUARD : tr("LONGSWORD_GUARD"),
#		item_table.Ids.GOLDEN_LONGSWORD_GUARD : tr("LONGSWORD_GUARD"),
#		item_table.Ids.FANTASIUM_LONGSWORD_GUARD : tr("LONGSWORD_GUARD"),
#
#		item_table.Ids.COPPER_RAPIER_BLADE : tr("RAPIER_BLADE"),
#		item_table.Ids.IRON_RAPIER_BLADE : tr("RAPIER_BLADE"),
#		item_table.Ids.SILVER_RAPIER_BLADE : tr("RAPIER_BLADE"),
#		item_table.Ids.GOLDEN_RAPIER_BLADE : tr("RAPIER_BLADE"),
#		item_table.Ids.FANTASIUM_RAPIER_BLADE : tr("RAPIER_BLADE"),
#		item_table.Ids.COPPER_RAPIER_HANDLE : tr("RAPIER_HANDLE"),
#		item_table.Ids.IRON_RAPIER_HANDLE : tr("RAPIER_HANDLE"),
#		item_table.Ids.SILVER_RAPIER_HANDLE : tr("RAPIER_HANDLE"),
#		item_table.Ids.GOLDEN_RAPIER_HANDLE : tr("RAPIER_HANDLE"),
#		item_table.Ids.FANTASIUM_RAPIER_HANDLE : tr("RAPIER_HANDLE"),
#		item_table.Ids.COPPER_RAPIER_BOLSTER : tr("RAPIER_BOLSTER"),
#		item_table.Ids.IRON_RAPIER_BOLSTER : tr("RAPIER_BOLSTER"),
#		item_table.Ids.SILVER_RAPIER_BOLSTER : tr("RAPIER_BOLSTER"),
#		item_table.Ids.GOLDEN_RAPIER_BOLSTER : tr("RAPIER_BOLSTER"),
#		item_table.Ids.FANTASIUM_RAPIER_BOLSTER : tr("RAPIER_BOLSTER"),
#		item_table.Ids.COPPER_RAPIER_GUARD : tr("RAPIER_GUARD"),
#		item_table.Ids.IRON_RAPIER_GUARD : tr("RAPIER_GUARD"),
#		item_table.Ids.SILVER_RAPIER_GUARD : tr("RAPIER_GUARD"),
#		item_table.Ids.GOLDEN_RAPIER_GUARD : tr("RAPIER_GUARD"),
#		item_table.Ids.FANTASIUM_RAPIER_GUARD : tr("RAPIER_GUARD")
	}

onready var default_phrases = [
	tr("ORDER_1"),
	tr("ORDER_2"),
	tr("ORDER_3"),
	tr("ORDER_4"),
	tr("ORDER_5"),
	tr("ORDER_6"),
	tr("ORDER_7"),
	tr("ORDER_8"),
	tr("ORDER_9"),
	tr("ORDER_10"),
	tr("ORDER_11"),
]

func _ready():
	pass
